// Turns the stored HTML snapshot into one recipient's copy: token substitution,
// link rewriting for click tracking, an open pixel, and a real unsubscribe URL.
//
// The HTML itself is generated by the client (src/domains/mail/html/generate.ts)
// and snapshotted onto the mail at send time. Nothing here re-renders the
// document, so there is no second generator to drift out of sync with the first.

import { mintToken } from './signing.ts'
import { env } from './env.ts'

export type RecipientContext = {
  mailId: string
  recipientId: string
  email: string
  fields: Record<string, string>
  businessName: string
}

// Matches TOKENS in src/domains/mail/tokens.ts. Anything unresolved collapses to
// an empty string rather than shipping a literal {{firstName}} to an inbox.
const buildTokenValues = (ctx: RecipientContext, unsubscribeUrl: string): Record<string, string> => ({
  firstName: '',
  lastName: '',
  // CSV columns come next, so an import can supply any custom token it likes...
  ...ctx.fields,
  // ...but these three are ours. Listing them last means a stray "email" or
  // "unsubscribeUrl" column in someone's spreadsheet cannot hijack the address
  // we send to or the link that opts them out.
  email: ctx.email,
  businessName: ctx.businessName,
  unsubscribeUrl,
})

const escapeHtml = (value: string): string =>
  value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')

export const substituteTokens = (html: string, values: Record<string, string>): string =>
  // Values land inside markup, so they are escaped. A CSV column containing
  // "<script>" is data, not a payload.
  html.replace(/\{\{(\w+)\}\}/g, (_match, key: string) => escapeHtml(values[key] ?? ''))

const ABSOLUTE_URL = /^https?:\/\//i

/**
 * Rewrites every outbound href through the click endpoint.
 *
 * Skipped deliberately:
 *  - the unsubscribe link (already signed, and wrapping it would log an
 *    unsubscribe as a click)
 *  - mailto:, tel:, and anchor links, which have no click semantics
 */
export const rewriteLinks = (html: string, token: string, unsubscribeUrl: string): string => {
  const base = env.functionsBaseUrl()
  return html.replace(/href="([^"]*)"/gi, (match, rawUrl: string) => {
    const url = rawUrl.trim()
    if (!ABSOLUTE_URL.test(url)) return match
    if (url === unsubscribeUrl) return match
    const tracked = `${base}/track/click?t=${encodeURIComponent(token)}&u=${encodeURIComponent(url)}`
    return `href="${tracked}"`
  })
}

const openPixel = (token: string): string => {
  const base = env.functionsBaseUrl()
  return (
    `<img src="${base}/track/open?t=${encodeURIComponent(token)}" ` +
    `width="1" height="1" alt="" ` +
    `style="display:block;width:1px;height:1px;border:0;outline:none;text-decoration:none" />`
  )
}

export const personalize = async (html: string, ctx: RecipientContext): Promise<string> => {
  const token = await mintToken({ mailId: ctx.mailId, recipientId: ctx.recipientId })
  const base = env.functionsBaseUrl()
  const unsubscribeUrl = `${base}/track/unsubscribe?t=${encodeURIComponent(token)}`

  // Order matters. Tokens are substituted first so that {{unsubscribeUrl}}
  // becomes a real href before link rewriting inspects the markup, and so a
  // token value can never be mistaken for a URL to rewrite.
  let out = substituteTokens(html, buildTokenValues(ctx, unsubscribeUrl))
  out = rewriteLinks(out, token, unsubscribeUrl)

  const pixel = openPixel(token)
  out = out.includes('</body>') ? out.replace('</body>', `${pixel}</body>`) : out + pixel

  return out
}

export const personalizeSubject = (subject: string, ctx: RecipientContext): string =>
  substituteTokens(subject, buildTokenValues(ctx, ''))
